name: my first workflow

on: push


jobs:   
    first_job:
        runs-on:    ubuntu-latest
        steps:  
        - name: welcome message
          run:  echo "hi this is my first github actions"
          
        - name: List files
          run: ls

        - name: Read file
          run: cat README.md