name: my first workflow

on: push


jobs:   
    build_job_1:
      runs-on:  ubuntu-latest
      steps:
      - name: install cowsay programm
        run: sudo apt-get install cowsay -y

      - name: execute Cowsay CMD
        run: cowsay -f dragon "Hi my name is aso and im a dragon" >> dragon.txt

      - name: upload dragon file
        uses: actions/upload-artifact@v4
        with:
          name: dragon
          path: dragon.txt
    
    test_job_2:
      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: download dragon file
        uses: actions/download-artifact@v4
        with:
          name: dragon
    deploy_job_3:
      needs: test_job_2
      runs-on: ubuntu-latest
      steps:
      - name: download dragon file
        uses: actions/download-artifact@v4
        with:
          name: dragon
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying....